mqtt:
  broker: 192.168.0.1
  port: 1883
  username: username
  password: password
  discovery_prefix: home_assistant

device:
  - type: led_rgb
    MAC: be:58:c0:00:6d:fc
    unique_id: bt_led_light_one
    name: First BT LED light
  - type: led_rgb
    MAC: ba:34:d8:00:8f:bb
    unique_id: bt_led_light_two
    name: Second BT LED light